INSERT INTO dictionary (custom_key, value, "group", use_custom_key) VALUES (NULL, 'Deactive', 'inventory-status', false);
INSERT INTO dictionary (custom_key, value, "group", use_custom_key) VALUES (NULL, 'Active', 'inventory-status', false);
INSERT INTO dictionary (custom_key, value, "group", use_custom_key) VALUES (NULL, 'Point to Point', 'inventory-topology', false);
INSERT INTO dictionary (custom_key, value, "group", use_custom_key) VALUES (NULL, 'Ring', 'inventory-topology', false);
INSERT INTO dictionary (custom_key, value, "group", use_custom_key) VALUES ( NULL, 'Tiered', 'inventory-bw-model', false);
INSERT INTO dictionary (custom_key, value, "group", use_custom_key) VALUES ( NULL, 'Ethernet', 'inventory-technology', false);
INSERT INTO dictionary (custom_key, value, "group", use_custom_key) VALUES ( NULL, 'Primary', 'inventory-prim-failover', false);
INSERT INTO dictionary (custom_key, value, "group", use_custom_key) VALUES ( NULL, 'Failover', 'inventory-prim-failover', false);
INSERT INTO dictionary (custom_key, value, "group", use_custom_key) VALUES ( NULL, 'Y', 'inventory-protected', false);
INSERT INTO dictionary (custom_key, value, "group", use_custom_key) VALUES ( NULL, 'N', 'inventory-protected', false);
INSERT INTO dictionary (custom_key, value, "group", use_custom_key) VALUES (NULL, 'Access', 'inventory-ckt-type', false);
INSERT INTO dictionary (custom_key, value, "group", use_custom_key) VALUES ( NULL, 'Customer', 'inventory-ckt-usage', false);
INSERT INTO dictionary (custom_key, value, "group", use_custom_key) VALUES ( NULL, 'Open (Past Due)', 'order-status', false);
INSERT INTO dictionary (custom_key, value, "group", use_custom_key) VALUES ( NULL, 'Completed', 'order-status', false);
INSERT INTO dictionary (custom_key, value, "group", use_custom_key) VALUES ( NULL, 'Circuits', 'order-type', false);
INSERT INTO dictionary custom_key, value, "group", use_custom_key) VALUES ( NULL, 'Open (On-Time)', 'order-status', false);
INSERT INTO dictionary ( custom_key, value, "group", use_custom_key) VALUES (NULL, 'Point to Point', 'inventory-topology', false);
INSERT INTO dictionary ( custom_key, value, "group", use_custom_key) VALUES (NULL, 'Ring', 'inventory-topology', false);
